### ISSUE TITLE
Make testimonial carousel periodic (re-entrant)

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#6]
### Description
Currently, one can scroll to the left and end with Bridget's testimonial, and there is no option to continue scrolling to left. One can also scroll to the right and end with Christine's testimonial. It would be nice to be able to scroll to the right of Christine's testimonial and end up with Bridget's, and vice versa (continue scrolling to left of Bridget's testimonial and end up in Christine's). 

### Visual Aid
One cannot continue scrolling to the right of Christine's testimonial, as it can be seen from screenshot:

<img width="350" alt="Screenshot 2024-05-22 at 5 36 17 PM" src="https://github.com/OPENDAP/Website/assets/8241481/c758c0e1-e857-409d-bf2e-cc95edf75c02">

### Page URL 
HOMEPAGE/use-cases/access-data/

**Comment by Mikejmnez** [comment]
@jahattox Is this a feature that is possible to set up?

**Comment by jahattox** [comment]
@Mikejmnez This should be fixed now

**Comment by Mikejmnez** [comment]
@jahattox I gave it a try, and I still cannot continue clicking towards the right to go from Christine's to Bridget's testimonials with one click (or one-click to the left to go from Bridget's to Christine's). Perhaps the feature was added but the website is taking longer to update? I tried clearing my cookies, and refreshing the website many times, but I still cannot see that periodic feature implemented. Thanks :)

**Comment by jahattox** [comment]
@Mikejmnez Are you using Chrome, by chance? If so, try following these instructions to see if it works: https://www.loom.com/share/a1b17c1ce9d149c89b0b5407822a1ecd?sid=2b9f21ed-0df0-4ca2-9f72-979af49b7c6e

If you're not using Chrome, let me know, and I'll try another fix.

**Comment by Mikejmnez** [comment]
Thanks @jahattox for the helpful resource. I cleared the cache and it indeed works!

Setting this up as solved
